config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :events
    resources :user_ones
    resources :user_twos
    resources :user_threes
    resources :event_ones
    resources :event_threes
    resources :settings

    root to: "events#index"
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "events#index"
  get '/events/1', to: 'events#show_one'
  get '/events/2', to: 'events#show_two'
  get '/events/3', to: 'events#show_three'

  get '/events/1/apply', to: 'events#apply_one'
  get '/events/2/apply', to: 'events#apply_two'
  get '/events/3/apply', to: 'events#apply_three'

  post '/users/1/submit', to: 'user_ones#submit_user_one'
  post '/users/2/new', to: 'user_twos#create_user_two'
  post '/users/2/submit', to: 'user_twos#submit_user_two'
  post '/users/3/submit', to: 'user_threes#submit_user_three'

  get '/user_one/export', to: 'user_ones#export_csv'
  get '/user_two/export', to: 'user_twos#export_csv'
  get '/user_three/export', to: 'user_threes#export_csv'

  get '/user_one/destroy_all', to: 'user_ones#destroy_all'
  get '/user_two/destroy_all', to: 'user_twos#destroy_all'
  get '/user_three/destroy_all', to: 'user_threes#destroy_all'

  get '/image_background/destroy', to: 'events#destroy_background'

  get '/finished', to: 'events#finished'
end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this
# `Administrate::ApplicationController`, making it the ideal place to put
# authentication logic or other before_actions.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
    http_basic_authenticate_with(
      name: ENV.fetch("ADMIN_NAME"),
      password: ENV.fetch("ADMIN_PASSWORD")
    )
    # before_action :authenticate_admin

    # def authenticate_admin
    #   # TODO Add authentication logic here.
    # end

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/application/_collection.html.erb
<%#
# Collection

This partial is used on the `index` and `show` pages
to display a collection of resources in an HTML table.

## Local variables:

- `collection_presenter`:
  An instance of [Administrate::Page::Collection][1].
  The table presenter uses `ResourceDashboard::COLLECTION_ATTRIBUTES` to determine
  the columns displayed in the table
- `resources`:
  An ActiveModel::Relation collection of resources to be displayed in the table.
  By default, the number of resources is limited by pagination
  or by a hard limit to prevent excessive page load times

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Collection
%>

<table aria-labelledby="<%= table_title %>">
  <thead>
    <tr>
      <% collection_presenter.attribute_types.each do |attr_name, attr_type| %>
        <th class="cell-label
        cell-label--<%= attr_type.html_class %>
        cell-label--<%= collection_presenter.ordered_html_class(attr_name) %>"
        scope="col"
        role="columnheader"
        aria-sort="<%= sort_order(collection_presenter.ordered_html_class(attr_name)) %>">
        <%= link_to(sanitized_order_params(page, collection_field_name).merge(
          collection_presenter.order_params_for(attr_name, key: collection_field_name)
        )) do %>
        <%= t(
          "helpers.label.#{collection_presenter.resource_name}.#{attr_name}",
          default: attr_name.to_s,
        ).titleize %>
            <% if collection_presenter.ordered_by?(attr_name) %>
              <span class="cell-label__sort-indicator cell-label__sort-indicator--<%= collection_presenter.ordered_html_class(attr_name) %>">
                <svg aria-hidden="true">
                  <use xlink:href="#icon-up-caret" />
                </svg>
              </span>
            <% end %>
          <% end %>
        </th>
      <% end %>
      <% [valid_action?(:edit, collection_presenter.resource_name),
          valid_action?(:destroy, collection_presenter.resource_name)].count(true).times do %>
        <th scope="col"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% resources.each do |resource| %>
      <tr class="js-table-row"
          <% if show_action? :show, resource %>
            <%= %(tabindex=0 role=link data-url=#{polymorphic_path([namespace, resource])}) %>
          <% end %>
          >
        <% collection_presenter.attributes_for(resource).each do |attribute| %>
          <td class="cell-data cell-data--<%= attribute.html_class %>">
            <% if show_action? :show, resource -%>
              <a href="<%= polymorphic_path([namespace, resource]) -%>"
                 tabindex="-1"
                 class="action-show"
                 >
                <%= render_field attribute %>
              </a>
            <% else %>
              <%= render_field attribute %>
            <% end -%>
          </td>
        <% end %>

        <% if valid_action? :edit, collection_presenter.resource_name %>
          <td><%= link_to(
            t("administrate.actions.edit"),
            [:edit, namespace, resource],
            class: "action-edit",
          ) if show_action? :edit, resource%></td>
        <% end %>

        <% if !(collection_presenter.resource_name == "event" && resource.id <= 3) && collection_presenter.resource_name != "event_one" && collection_presenter.resource_name != "event_two" && collection_presenter.resource_name != "setting" %>
          <% if valid_action? :destroy, collection_presenter.resource_name %>
            <td><%= link_to(
              t("administrate.actions.destroy"),
              [namespace, resource],
              class: "text-color-red",
              method: :delete,
              data: { confirm: t("administrate.actions.confirm") }
            ) if show_action? :destroy, resource %></td>
          <% end %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/application/_form.html.erb
<%#
# Form Partial

This partial is rendered on a resource's `new` and `edit` pages,
and renders all form fields for a resource's editable attributes.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Form][1].
  Contains helper methods to display a form,
  and knows which attributes should be displayed in the resource's form.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Form
%>

<%= form_for([namespace, page.resource], html: { class: "form" }) do |f| %>
  <% if page.resource.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= t(
          "administrate.form.errors",
          pluralized_errors: pluralize(page.resource.errors.count, t("administrate.form.error")),
          resource_name: display_resource_name(page.resource_name).singularize
        ) %>
      </h2>

      <ul>
        <% page.resource.errors.full_messages.each do |message| %>
          <li class="flash-error"><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% page.attributes.each do |attribute| -%>
    <div class="field-unit field-unit--<%= attribute.html_class %> field-unit--<%= requireness(attribute) %>">
    
      <% if attribute.name.start_with?("image") %>
           
        <div class="field-unit__label">
          <label for="product_link"><%= t(
            "helpers.label.#{resource_name}.#{attribute.name}",
            default: attribute.name.titleize,
          ) %></label>
        </div>
        <div class="field-unit__field">
          <%= f.file_field attribute.name.to_sym, direct_upload: true %>
        </div>
        
      <% else %>
        <%= render_field attribute, f: f %>
      <% end %>

    </div>
  <% end -%>

  <div class="form-actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/application/index.html.erb
<%#
# Index

This view is the template for the index page.
It is responsible for rendering the search bar, header and pagination.
It renders the `_table` partial to display details about the resources.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Collection][1].
  Contains helper methods to help display a table,
  and knows which attributes should be displayed in the resource's table.
- `resources`:
  An instance of `ActiveRecord::Relation` containing the resources
  that match the user's search criteria.
  By default, these resources are passed to the table partial to be displayed.
- `search_term`:
  A string containing the term the user has searched for, if any.
- `show_search_bar`:
  A boolean that determines if the search bar should be shown.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Collection
%>

<% content_for(:title) do %>
  <%= display_resource_name(page.resource_name) %>
<% end %>

<header class="main-content__header" role="banner">
  <h1 class="main-content__page-title" id="page-title">
    <%= content_for(:title) %>
  </h1>

  <% if show_search_bar %>
    <%= render(
      "search",
      search_term: search_term,
      resource_name: display_resource_name(page.resource_name)
    ) %>
  <% end %>

  <% if page.resource_name == "user_one" %>
    <a style="margin-right: 1rem" class="button mr-2" href="/user_one/destroy_all" onclick="return confirm('정말 모두 삭제하시겠습니까?')">전체 삭제</a>
  <% elsif page.resource_name == "user_two" %>
    <a style="margin-right: 1rem" class="button mr-2" href="/user_two/destroy_all" onclick="return confirm('정말 모두 삭제하시겠습니까?')">전체 삭제</a>
  <% elsif page.resource_name == "user_three" %>
    <a style="margin-right: 1rem" class="button mr-2" href="/user_three/destroy_all" onclick="return confirm('정말 모두 삭제하시겠습니까?')">전체 삭제</a>
  <% end %>

  <% if page.resource_name == "event" %>
    <div>
      <%= link_to(
        t(
          "administrate.actions.new_resource",
          name: page.resource_name.titleize.downcase
        ),
        [:new, namespace, page.resource_path],
        class: "button",
      ) if valid_action?(:new) && show_action?(:new, new_resource) %>
    </div>
  <% elsif page.resource_name == "user_one" %>
    <%= link_to("CSV로 저장", user_one_export_path(format: "csv"), { :class => "button" } ) %>
  <% elsif page.resource_name == "user_two" %>
    <%= link_to("CSV로 저장", user_two_export_path(format: "csv"), { :class => "button" } ) %>
    <% elsif page.resource_name == "user_three" %>
    <%= link_to("CSV로 저장", user_three_export_path(format: "csv"), { :class => "button" } ) %>
  <% end %>

</header>

<section class="main-content__body main-content__body--flush">
  <%= render(
    "collection",
    collection_presenter: page,
    collection_field_name: resource_name,
    page: page,
    resources: resources,
    table_title: "page-title"
  ) %>

  <%= paginate resources %>
</section>

app/views/admin/application/new.html.erb
<%#
# New

This view is the template for the "new resource" page.
It displays a header, and then renders the `_form` partial
to do the heavy lifting.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Form][1].
  Contains helper methods to help display a form,
  and knows which attributes should be displayed in the resource's form.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Form
%>

<% content_for(:title) do %>
  <%= t(
    "administrate.actions.new_resource",
    name: display_resource_name(page.resource_name).titleize
  ) %>
<% end %>

<header class="main-content__header" role="banner">
  <h1 class="main-content__page-title">
    <%= content_for(:title) %>
  </h1>

  <div>
    <%= link_to t("administrate.actions.back"), :back, class: "button" %>
  </div>
</header>

<section class="main-content__body">
  <%= render "form", page: page %>
</section>

app/views/admin/application/show.html.erb
<%#
# Show

This view is the template for the show page.
It renders the attributes of a resource,
as well as a link to its edit page.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Show][1].
  Contains methods for accessing the resource to be displayed on the page,
  as well as helpers for describing how each attribute of the resource
  should be displayed.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Show
%>

<% content_for(:title) { t("administrate.actions.show_resource", name: page.page_title) } %>

<header class="main-content__header" role="banner">
  <h1 class="main-content__page-title">
    <%= content_for(:title) %>
  </h1>

  <div>
    <%= link_to(
      t("administrate.actions.edit_resource", name: page.page_title),
      [:edit, namespace, page.resource],
      class: "button",
    ) if valid_action?(:edit) && show_action?(:edit, page.resource) %>
  </div>
</header>

<section class="main-content__body">
  <dl>
    <% page.attributes.each do |attribute| %>
      <dt class="attribute-label" id="<%= attribute.name %>">
      <%= t(
        "helpers.label.#{resource_name}.#{attribute.name}",
        default: attribute.name.titleize,
      ) %>
      </dt>

      <dd class="attribute-data attribute-data--<%=attribute.html_class%>">
        
        <% if attribute.name.start_with?("image") %>
          <% image_key = attribute.data.try(:key) %>
          <% if image_key.nil? %>
            디폴트 이미지 사용중
          <% else %>
            <img src="<%= Cloudinary::Utils.cloudinary_url(image_key, options = {}) %>"/>
            
            <% if attribute.name == "image_background" %>
              <%= link_to "현재 이미지 삭제", image_background_destroy_path(format: :js), format: :js, remote: true, class: "btn" %>
            <% end %>
          
          <% end %>
        <% else %>
          <%= render_field attribute, page: page %>
        <% end %>

      </dd>
    <% end %>
  </dl>
</section>